export default {
  GET_BOATS: 'GET_BOATS',
  GET_BOATS_REQUEST: 'GET_BOATS_REQUEST',
  GET_BOATS_SUCCESS: 'GET_BOATS_SUCCESS',
  GET_BOATS_FAILURE: 'GET_BOATS_FAILURE',

  GET_MY_BOATS: 'GET_MY_BOATS',
  GET_MY_BOATS_REQUEST: 'GET_MY_BOATS_REQUEST',
  GET_MY_BOATS_SUCCESS: 'GET_MY_BOATS_SUCCESS',
  GET_MY_BOATS_FAILURE: 'GET_MY_BOATS_FAILURE',

  GET_BOAT: 'GET_BOAT',
  GET_BOAT_REQUEST: 'GET_BOAT_REQUEST',
  GET_BOAT_SUCCESS: 'GET_BOAT_SUCCESS',
  GET_BOAT_FAILURE: 'GET_BOAT_FAILURE',

  GET_BOAT_TIMES: 'GET_BOAT_TIMES',
  GET_BOAT_TIMES_REQUEST: 'GET_BOAT_TIMES_REQUEST',
  GET_BOAT_TIMES_SUCCESS: 'GET_BOAT_TIMES_SUCCESS',
  GET_BOAT_TIMES_FAILURE: 'GET_BOAT_TIMES_FAILURE',

  CREATE_BOAT: 'CREATE_BOAT',
  CREATE_BOAT_REQUEST: 'CREATE_BOAT_REQUEST',
  CREATE_BOAT_SUCCESS: 'CREATE_BOAT_SUCCESS',
  CREATE_BOAT_FAILURE: 'CREATE_BOAT_FAILURE',

  UPDATE_BOAT: 'UPDATE_BOAT',
  UPDATE_BOAT_REQUEST: 'UPDATE_BOAT_REQUEST',
  UPDATE_BOAT_SUCCESS: 'UPDATE_BOAT_SUCCESS',
  UPDATE_BOAT_FAILURE: 'UPDATE_BOAT_FAILURE',

  UPDATE_BOAT_IMAGE: 'UPDATE_BOAT_IMAGE',
  UPDATE_BOAT_IMAGE_REQUEST: 'UPDATE_BOAT_IMAGE_REQUEST',
  UPDATE_BOAT_IMAGE_SUCCESS: 'UPDATE_BOAT_IMAGE_SUCCESS',
  UPDATE_BOAT_IMAGE_FAILURE: 'UPDATE_BOAT_IMAGE_FAILURE',

  UPDATE_BOAT_LOCATIONS: 'UPDATE_BOAT_LOCATIONS',
  UPDATE_BOAT_LOCATIONS_REQUEST: 'UPDATE_BOAT_LOCATIONS_REQUEST',
  UPDATE_BOAT_LOCATIONS_SUCCESS: 'UPDATE_BOAT_LOCATIONS_SUCCESS',
  UPDATE_BOAT_LOCATIONS_FAILURE: 'UPDATE_BOAT_LOCATIONS_FAILURE',

  GET_BOOKMARKS: 'GET_BOOKMARKS',
  GET_BOOKMARKS_REQUEST: 'GET_BOOKMARKS_REQUEST',
  GET_BOOKMARKS_SUCCESS: 'GET_BOOKMARKS_SUCCESS',
  GET_BOOKMARKS_FAILURE: 'GET_BOOKMARKS_FAILURE',

  CREATE_BOOKMARK: 'CREATE_BOOKMARK',
  CREATE_BOOKMARK_REQUEST: 'CREATE_BOOKMARK_REQUEST',
  CREATE_BOOKMARK_SUCCESS: 'CREATE_BOOKMARK_SUCCESS',
  CREATE_BOOKMARK_FAILURE: 'CREATE_BOOKMARK_FAILURE',

  DESTROY_BOOKMARK: 'DESTROY_BOOKMARK',
  DESTROY_BOOKMARK_REQUEST: 'DESTROY_BOOKMARK_REQUEST',
  DESTROY_BOOKMARK_SUCCESS: 'DESTROY_BOOKMARK_SUCCESS',
  DESTROY_BOOKMARK_FAILURE: 'DESTROY_BOOKMARK_FAILURE',
};
