export default {
  CREATE_MARINA: 'CREATE_MARINA',
  CREATE_MARINA_REQUEST: 'CREATE_MARINA_REQUEST',
  CREATE_MARINA_SUCCESS: 'CREATE_MARINA_SUCCESS',
  CREATE_MARINA_FAILURE: 'CREATE_MARINA_FAILURE',

  GET_MARINA: 'GET_MARINA',
  GET_MARINA_REQUEST: 'GET_MARINA_REQUEST',
  GET_MARINA_SUCCESS: 'GET_MARINA_SUCCESS',
  GET_MARINA_FAILURE: 'GET_MARINA_FAILURE',

  GET_MARINAS: 'GET_MARINAS',
  GET_MARINAS_REQUEST: 'GET_MARINAS_REQUEST',
  GET_MARINAS_SUCCESS: 'GET_MARINAS_SUCCESS',
  GET_MARINAS_FAILURE: 'GET_MARINAS_FAILURE',
};
