export default {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  SIGNUP_USER: 'SIGNUP_USER',
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  RESET_PASSWORD: 'RESET_PASSWORD',
  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  UPDATE_PROFILE_PICTURE: 'UPDATE_PROFILE_PICTURE',
  UPDATE_PROFILE_PICTURE_REQUEST: 'UPDATE_PROFILE_PICTURE_REQUEST',
  UPDATE_PROFILE_PICTURE_SUCCESS: 'UPDATE_PROFILE_PICTURE_SUCCESS',
  UPDATE_PROFILE_PICTURE_FAILURE: 'UPDATE_PROFILE_PICTURE_FAILURE',

  UPDATE_BOAT_DATES: 'UPDATE_BOAT_DATES',
  UPDATE_BOAT_DATES_REQUEST: 'UPDATE_BOAT_DATES_REQUEST',
  UPDATE_BOAT_DATES_SUCCESS: 'UPDATE_BOAT_DATES_SUCCESS',
  UPDATE_BOAT_DATES_FAILURE: 'UPDATE_BOAT_DATES_FAILURE',
};
